创建ndarray数组

In [1]:
import numpy as np

In [4]:
data1=[5,7,9,20] #列表
arr1=np.array(data1)
arr1

array([ 5,  7,  9, 20])

In [5]:
data2=(5,7,9,20)
arr2=np.array(data2)
arr2

array([ 5,  7,  9, 20])

In [23]:
data3=[[1,3,4,5],[5,6,7,8]] #多维数组
arr3=np.array(data3)
arr3

array([[1, 3, 4, 5],
       [5, 6, 7, 8]])

In [28]:
arr5=np.ones_like(arr3)
arr5
#arr5.dtype

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [4]:
arr3.shape

(2, 4)

In [5]:
arr3.dtype

dtype('int64')

In [6]:
data4=[1,3,4.34,5]
arr4=np.array(data4)
arr4

array([1.  , 3.  , 4.34, 5.  ])

In [8]:
arr4.dtype

dtype('float64')

In [9]:
#zeros函数:可以创建指定长度或形状的全0数组
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
#ones函数:ones函数可以创建指定长度或形状的全1数组
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [21]:
#empty函数：empty函数可以创建一个没有具体值的数组（随机垃圾数组）?????
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [22]:
#arange函数
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1=np.arange(10)  #dtype("int32")
a2=np.ones(5)     #dtype("float64")
a3=a1.astype(a2.dtype)
a3.dtype

dtype('float64')

In [31]:
#数据重塑：对于定义好的数组，可以通过reshape方法改变其数据维度(传入参数是新维度元组）
arr=np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
#多维数组重塑
arr=np.array([[3,4,5],[1,2,3]])
arr.reshape((3,2))

array([[3, 4],
       [5, 1],
       [2, 3]])

In [35]:
#reshape参数设置为-1，
arr=np.arange(12)
arr.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
arr=np.arange(10).reshape((5,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
#数据散开(ravel)
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#数据扁平化
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
#数组合并：数组合并用于几个数组间的操作，concatenate方法通过指定轴方向，将多个数组合并在一起。
arr1=np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
arr2=np.arange(12,24).reshape(3,4)
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
np.concatenate([arr1,arr2],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
np.concatenate([arr1,arr2],axis=1)

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [49]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
np.hstack((arr1,arr2))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [51]:
#数据拆分
arr=np.arange(12).reshape((6,2))
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [57]:
np.split(arr,2,axis=0) #arr要切分的数组，2：要切分的个数，axis=0:横向切分，axis=1：纵向切分

[array([[0, 1],
        [2, 3],
        [4, 5]]), array([[ 6,  7],
        [ 8,  9],
        [10, 11]])]

In [59]:
#数组转置
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [61]:
#随机函数--randint函数生成整数随机数
arr=np.random.randint(100,200,size=(5,4))
arr

array([[128, 163, 164, 174],
       [155, 159, 146, 103],
       [188, 170, 161, 149],
       [134, 188, 163, 137],
       [170, 117, 124, 130]])

In [62]:
#概率分布函数randn()函数（生成平均数0，标准差1的正态分布随机数）
arr=np.random.randn(2,3,5)
arr

array([[[-1.01587144, -0.66092904,  0.4492047 ,  2.03568245,
         -0.53971176],
        [-0.38196741,  1.08510934, -1.0164344 ,  0.70149669,
         -0.89192139],
        [-0.90870799,  1.56874414,  1.10950449,  1.9620953 ,
          1.470036  ]],

       [[-0.24276281,  0.80180392, -0.29980681,  0.29030823,
          2.27503704],
        [ 0.63552007, -1.40739109,  1.67066895, -0.58228972,
         -0.30611586],
        [ 1.08047363,  0.68920272, -0.51580579, -0.61450835,
         -0.26321721]]])

In [63]:
#normal函数生成指定均值和标准差的正态分布数组
arr=np.random.normal(4,5,size=(3,5))
arr

array([[ 5.88009043, -2.84474929, -0.41429477,  4.78821325,  5.55403689],
       [ 8.80660625,  6.8991605 ,  1.2762883 ,  5.52641865,  0.35766959],
       [-5.57583751,  5.45101773,  8.77475297,  2.88425677,  6.82823411]])

#数组的索引和切片

In [64]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
print(arr[3])
print(arr[-1])
arr[2]=123
arr

3
9


array([  0,   1, 123,   3,   4,   5,   6,   7,   8,   9])

In [77]:
arr1=arr[-3:-1]
arr1

array([77, 77])

In [78]:
arr1[:]=77
arr

array([  0,   1, 123,   3,   4,   5,   6,  77,  77,   9])

In [79]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
print(arr[0])
print(arr[2])

[0 1 2 3 4]
[10 11 12 13 14]


In [84]:
print(arr[0][3])
print(arr[0,3])

3
3


In [89]:
arr=np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [93]:
arr[:,1].shape

(4,)

In [94]:
arr[:,1:2].shape

(4, 1)

In [90]:
arr[2:]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [103]:
fruits=np.array(['apple','banana','pear','banana','pear','apple','pear'])
datas=np.random.randint(-1,1,size=(7,5))
print(datas)
datas[fruits=='pear']

[[ 0  0 -1  0 -1]
 [ 0  0  0 -1  0]
 [-1  0  0  0 -1]
 [ 0 -1 -1  0  0]
 [ 0 -1  0  0  0]
 [ 0  0  0 -1  0]
 [-1 -1  0 -1 -1]]


array([[-1,  0,  0,  0, -1],
       [ 0, -1,  0,  0,  0],
       [-1, -1,  0, -1, -1]])

In [104]:
arr[[1,3,2]]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 6,  7,  8]])

In [108]:
arr=np.random.randn(3,3)
arr

array([[ 0.64724242, -0.24651749,  1.91634943],
       [-1.87639633, -0.57295965, -1.07366456],
       [ 0.98604256, -0.86015073, -2.20365759]])

In [109]:
#求绝对值
np.abs(arr)

array([[0.64724242, 0.24651749, 1.91634943],
       [1.87639633, 0.57295965, 1.07366456],
       [0.98604256, 0.86015073, 2.20365759]])

In [110]:
#求平方
np.square(arr)

array([[0.41892275, 0.06077087, 3.67239514],
       [3.52086319, 0.32828276, 1.15275559],
       [0.97227993, 0.73985927, 4.85610677]])

In [111]:
#随机符合正态分布的数组正值替换成1，负值为-1
arr=np.random.randn(4,4)
arr

array([[-1.36780473,  0.52157987,  1.84043464,  0.08851328],
       [-1.1276705 , -0.24612622,  1.53499636, -1.15733819],
       [ 1.62363655, -0.0868268 , -0.69403189, -1.28882358],
       [-0.63634141,  1.2677374 ,  0.28262863, -1.39392571]])

In [112]:
new_arr = np.where(arr>0,1,-1)
new_arr

array([[-1,  1,  1,  1],
       [-1, -1,  1, -1],
       [ 1, -1, -1, -1],
       [-1,  1,  1, -1]])

In [113]:
arr=np.random.randint(1,300,size=(3,3))
arr

array([[180, 296,  99],
       [153, 295, 204],
       [148, 189, 197]])

In [115]:
new_arr=np.where(arr>200,3,np.where(arr>100,2,1))
new_arr

array([[2, 3, 1],
       [2, 3, 3],
       [2, 2, 2]])

In [118]:
print(arr.sum()) #函数求和
print(arr.mean())#函数求平均
print(arr.std())#函数求标准差

1761
195.66666666666666
61.220911460055866


In [120]:
#作用于列
print(arr.sum(axis=0))
arr.mean(axis=1)

[481 780 500]


array([191.66666667, 217.33333333, 178.        ])

In [122]:
#cumsum函数：逐行相加
arr.cumsum(axis=0)

array([[180, 296,  99],
       [333, 591, 303],
       [481, 780, 500]])

In [123]:
#cumprod 逐列相乘
arr.cumprod(1)

array([[    180,   53280, 5274720],
       [    153,   45135, 9207540],
       [    148,   27972, 5510484]])

In [124]:
#所用np.unique找到数组的唯一值
fruits=np.array(['apple','banana','pear','banana','pear','apple','pear'])
np.unique(fruits)

array(['apple', 'banana', 'pear'], dtype='<U6')

In [126]:
arr=np.array([2,3,3,2,4,2])
np.unique(arr)

array([2, 3, 4])

In [128]:
#使用numpy进行数组的存取--使用np.savetxt存储
arr=np.arange(12).reshape(4,3)
arr


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [129]:
np.savetxt('ch2exl.csv',arr,fmt='%d',delimiter=',')

In [138]:
#使用np.loadtxt方法进行读取
arr=np.loadtxt('ch2exl.csv',delimiter=',')
arr

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

# 综合案例--图像变换

In [1]:
from PIL import Image
import numpy as np

In [4]:
im=np.array(Image.open('/home/ysc/数据分析/data/第二讲/1.jpeg'))
print(im.shape,im.dtype)

(350, 583, 3) uint8


In [5]:
im

array([[[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ...,
        [198, 198, 198],
        [197, 197, 197],
        [196, 196, 196]],

       [[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ...,
        [198, 198, 198],
        [197, 197, 197],
        [196, 196, 196]],

       [[226, 226, 226],
        [226, 226, 226],
        [226, 226, 226],
        ...,
        [198, 198, 198],
        [197, 197, 197],
        [195, 195, 195]],

       ...,

       [[210, 210, 210],
        [211, 211, 211],
        [211, 211, 211],
        ...,
        [122, 122, 122],
        [124, 124, 124],
        [125, 125, 125]],

       [[211, 211, 211],
        [211, 211, 211],
        [211, 211, 211],
        ...,
        [120, 120, 120],
        [122, 122, 122],
        [124, 124, 124]],

       [[211, 211, 211],
        [211, 211, 211],
        [212, 212, 212],
        ...,
        [119, 119, 119],
        [121, 121, 121],
        [123, 123, 123]]

In [6]:
b=[255,255,255] -im #数组运算
new_im=Image.fromarray(a.astypw('uint8'))
new_im.save('/home/ysc/数据分析/data/第二讲/new_1.jpeg')

NameError: name 'a' is not defined